package org.example.technihongo.enums;

public enum ActivityType {
    LOGIN, LOGOUT, COMPLETE, CREATE, UPDATE, DELETE, ENROLL, START_QUIZ,
    VIEW, REGISTER_SUBSCRIPTION,RENEW_SUBSCRIPTION, SAVE, REMOVE, SWITCH, REPORT_FLASHCARD_SET,
    REPORT_RATING, HANDLE_REPORT, REMOVE_FAVORITE
}
